
# ===============================
# = DATA SOURCE
# Baza danych: mysql,
# User: jguard,
# Password: jguard
# Host: localhsot
# Port: 3306
#
# ===============================
spring:
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/jguard
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  queries:
    users-query:  select email, password, active from user where email=?
    roles-query:  select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?
# =============================
# Ścieżki do zapisu na dysku. W przypadku Windows:
# "C:\jguard\public\img\"
# Folder zostanie stworzony jeżeli nie istnieje!
# = Ex.: "/jguard/public/img/j_img_55/3.jpg"
# =============================
resources:
  public:
    img-dir: /jguard/public/img/
  img:
    jewelery-prefix: j_img_
    sufix: .jpg